# Generated by Django 5.2.8 on 2026-01-20 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_jp",
                    models.CharField(max_length=200, verbose_name="日本語タイトル"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="英語タイトル"
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="URL")),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=100, verbose_name="情報源"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="要約")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("business", "ビジネス"),
                            ("technology", "テクノロジー"),
                            ("science", "科学"),
                            ("health", "健康"),
                            ("sports", "スポーツ"),
                            ("entertainment", "エンターテイメント"),
                        ],
                        default="technology",
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="公開日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "full_content_flag",
                    models.BooleanField(
                        default=False, verbose_name="フルコンテンツ取得フラグ"
                    ),
                ),
                (
                    "content_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="コンテンツ更新日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "記事",
                "verbose_name_plural": "記事一覧",
                "ordering": ["-published_at"],
            },
        ),
    ]
