# Generated by Django 5.2.8 on 2026-01-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content_updated_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="full_content_flag",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title_en",
        ),
    ]
