# Generated by Django 5.2.8 on 2026-01-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0002_remove_article_content_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="ArticleModel",
        ),
    ]
