# Generated by Django 5.2.8 on 2026-01-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0003_rename_article_articlemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemodel",
            name="summary",
        ),
    ]
