# Generated by Django 5.2.8 on 2026-01-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0005_userkeyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userkeyword",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
