# Generated by Django 5.2.8 on 2026-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0006_alter_articlemodel_id_alter_userkeyword_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="概要"),
        ),
    ]
