# Generated by Django 5.2.8 on 2026-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0007_articlemodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="keyword_tag",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="検索キーワード"
            ),
        ),
    ]
