# Generated by Django 5.2.8 on 2026-01-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0008_articlemodel_keyword_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="画像URL"
            ),
        ),
    ]
