# Generated by Django 5.2.8 on 2026-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0009_articlemodel_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemodel",
            name="image_url",
        ),
    ]
