# Generated by Django 5.2.8 on 2026-01-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0010_remove_articlemodel_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="概要"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="articlemodel",
            name="keyword_tag",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="検索キーワード"
            ),
            preserve_default=False,
        ),
    ]
