# Generated by Django 5.2.8 on 2026-01-30 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0011_alter_articlemodel_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userkeyword",
            name="created_at",
        ),
        migrations.AddField(
            model_name="userkeyword",
            name="registered_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="マイキーワード登録日時"
            ),
        ),
        migrations.AlterField(
            model_name="userkeyword",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AlterField(
            model_name="userkeyword",
            name="word",
            field=models.CharField(max_length=100, verbose_name="マイキーワード"),
        ),
    ]
