# Generated by Django 5.2.8 on 2026-01-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0012_remove_userkeyword_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userkeyword",
            options={"ordering": ["-registered_at"]},
        ),
    ]
