# Generated by Django 5.2.8 on 2026-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0013_alter_userkeyword_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="title_jp",
            field=models.CharField(max_length=500, verbose_name="日本語タイトル"),
        ),
    ]
