# Generated by Django 5.2.8 on 2026-02-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0014_alter_articlemodel_title_jp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="url",
            field=models.TextField(unique=True, verbose_name="URL"),
        ),
    ]
