# Generated by Django 5.2.8 on 2026-02-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0015_alter_articlemodel_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
