# Generated by Django 5.2.8 on 2026-02-11 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0016_articlemodel_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("business", "ビジネス"),
                    ("technology", "テクノロジー"),
                    ("science", "科学"),
                    ("health", "健康"),
                    ("sports", "スポーツ"),
                    ("entertainment", "エンターテイメント"),
                    ("prefecture", "地域ニュース"),
                ],
                default="technology",
                max_length=20,
                verbose_name="カテゴリ",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hokkaido", "北海道"),
                            ("aomori", "青森県"),
                            ("iwate", "岩手県"),
                            ("miyagi", "宮城県"),
                            ("akita", "秋田県"),
                            ("yamagata", "山形県"),
                            ("fukushima", "福島県"),
                            ("ibaraki", "茨城県"),
                            ("tochigi", "栃木県"),
                            ("gunma", "群馬県"),
                            ("saitama", "埼玉県"),
                            ("chiba", "千葉県"),
                            ("tokyo", "東京都"),
                            ("kanagawa", "神奈川県"),
                            ("niigata", "新潟県"),
                            ("toyama", "富山県"),
                            ("ishikawa", "石川県"),
                            ("fukui", "福井県"),
                            ("yamanashi", "山梨県"),
                            ("nagano", "長野県"),
                            ("gifu", "岐阜県"),
                            ("shizuoka", "静岡県"),
                            ("aichi", "愛知県"),
                            ("mie", "三重県"),
                            ("shiga", "滋賀県"),
                            ("kyoto", "京都府"),
                            ("osaka", "大阪府"),
                            ("hyogo", "兵庫県"),
                            ("nara", "奈良県"),
                            ("wakayama", "和歌山県"),
                            ("tottori", "鳥取県"),
                            ("shimane", "島根県"),
                            ("okayama", "岡山県"),
                            ("hiroshima", "広島県"),
                            ("yamaguchi", "山口県"),
                            ("tokushima", "徳島県"),
                            ("kagawa", "香川県"),
                            ("ehime", "愛媛県"),
                            ("kochi", "高知県"),
                            ("fukuoka", "福岡県"),
                            ("saga", "佐賀県"),
                            ("nagasaki", "長崎県"),
                            ("kumamoto", "熊本県"),
                            ("oita", "大分県"),
                            ("miyazaki", "宮崎県"),
                            ("kagoshima", "鹿児島県"),
                            ("okinawa", "沖縄県"),
                        ],
                        help_text="お住まいの都道府県を選択してください",
                        max_length=20,
                        null=True,
                        verbose_name="都道府県",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザープロフィール",
                "verbose_name_plural": "ユーザープロフィール",
            },
        ),
    ]
