# Generated by Django 5.2.8 on 2026-02-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0017_alter_articlemodel_category_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="送信済みフラグ"),
        ),
    ]
