# Generated by Django 5.2.8 on 2026-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_collector", "0018_articlemodel_is_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_line_subscribed",
            field=models.BooleanField(
                default=False,
                help_text="チェックを入れると、選択した都道府県のニュースをLINEでお届けします",
                verbose_name="LINE通知を希望する",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="line_user_id",
            field=models.CharField(
                blank=True,
                help_text="LINEとの連携に使用します。自動で設定されるので入力不要です",
                max_length=100,
                null=True,
                verbose_name="LINEユーザーID",
            ),
        ),
    ]
